# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plc_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1925, 1017)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Set background colors and properties */\n"
"QFrame#mainFrame{\n"
"background-color: #f3f4f7;\n"
"}\n"
"\n"
"QFrame#contentFrame{\n"
"background-color: #fff;\n"
"}\n"
"\n"
"QFrame#leftMenuFrame{\n"
"background-color: #36647b;\n"
"}\n"
"\n"
"QWidget#page_License {\n"
"background-color: #f0f0f0;\n"
"}\n"
"\n"
"\n"
"QTextBrowser{\n"
"font: 12pt \"Open Sans\";\n"
"color:#171725;\n"
"background-color: #F7F8F9;\n"
"}\n"
"\n"
"QDateTimeEdit {\n"
"font-size: 12pt;\n"
"font:75  \"Open Sans\";\n"
"font-weight: Semibold;\n"
"color:#171725;\n"
"background-color: #F7F8F9;\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"font-size: 12pt;\n"
"font:75  \"Open Sans\";\n"
"font-weight: Semibold;\n"
"color:#171725;\n"
"background-color: #ECF1F7;\n"
"/*font-family: Noto Sans;*/\n"
"}\n"
"\n"
"QTextEdit{\n"
"color:#171725;\n"
"background-color: #F7F8F9;\n"
"font: 10pt \"Open Sans\";\n"
"}\n"
"\n"
"\n"
"QWidget{\n"
"background-color: #F7F8F9;\n"
"}\n"
"\n"
"\n"
"/************************************************/\n"
"QTableWidget {\n"
"    font-family: Open Sans;\n"
"    font-size: 20pt;\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #E5E5E5;\n"
"    color: #171725;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font-size: 14pt;\n"
"    height: 40px;  /* Set all cells to 40px height */\n"
"    border: 1px solid #cccccc;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"\n"
"/* Alternate row coloring for visual distinction */\n"
"QTableWidget::item:nth-child(odd) {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"/* Highlight selected row */\n"
"QTableWidget::item:selected {\n"
"    background-color: #d3d3d3;\n"
"}\n"
"\n"
"/************************************************/\n"
"/*\n"
"QTableView{\n"
"color:#171725;\n"
"background-color: #ECF1F7;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section { \n"
"font: 75 10pt \"Open Sans\";\n"
"color: white;\n"
"background-color:#989898; \n"
"}\n"
"\n"
"QTableView::item { \n"
"font: 75 12pt \"Open Sans\";\n"
"color:white; \n"
"background:#2f373d; \n"
"font-weight:900; \n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"font: 75 12pt \"open Sans\"; \n"
"color:black; \n"
"background:#7cc8b9; \n"
"font-weight:900; \n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"*/\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox{\n"
"text-align: center;\n"
"border-radius: 5px;\n"
"border:2px solid #D7DBEC;\n"
"color: #000000;\n"
"padding: 2px;\n"
"font-weight: bold;\n"
"font-family: Open Sans;\n"
"font-size: 10pt;\n"
"height:40px;\n"
"width:150px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1901, 1080))
        self.widget.setStyleSheet("background-color: #F7F8F9;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1871, 51))
        self.widget_2.setStyleSheet("\n"
"Qlabel{\n"
" font: 75 14pt \"Open Sans\";\n"
" color:#103782;\n"
" text-align:left;\n"
" height:40px;\n"
" padding-left:10px;\n"
"}\n"
"\n"
"QPushButton{\n"
" font: 75 14pt \"Open Sans\" ;\n"
" color:#171725;\n"
" text-align:left;\n"
" height:52px;\n"
" width : 250px;\n"
" border :none;\n"
" padding-left:10px;\n"
"padding-right:10px;\n"
"\n"
"\n"
"}\n"
"QWidget{\n"
"background-color: #F7F8F9;\n"
"border-bottom-color:rgba(174, 177, 181,100);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.navImp_2 = QtWidgets.QPushButton(self.widget_2)
        self.navImp_2.setGeometry(QtCore.QRect(34, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navImp_2.setFont(font)
        self.navImp_2.setStyleSheet("border: none; \n"
"")
        self.navImp_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Skew_name_sample__1_-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navImp_2.setIcon(icon)
        self.navImp_2.setIconSize(QtCore.QSize(80, 80))
        self.navImp_2.setCheckable(True)
        self.navImp_2.setAutoExclusive(True)
        self.navImp_2.setObjectName("navImp_2")
        self.navImp_3 = QtWidgets.QPushButton(self.widget_2)
        self.navImp_3.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navImp_3.setFont(font)
        self.navImp_3.setStyleSheet("border: none; \n"
"")
        self.navImp_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Logo_mixed_colour_sample1-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navImp_3.setIcon(icon1)
        self.navImp_3.setIconSize(QtCore.QSize(30, 30))
        self.navImp_3.setCheckable(True)
        self.navImp_3.setAutoExclusive(True)
        self.navImp_3.setObjectName("navImp_3")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 51, 271, 961))
        self.widget_3.setStyleSheet("QWidget{\n"
"background-color:  #F7F8F9;\n"
"}\n"
"QWidget{\n"
"border-right-color:rgba(174, 177, 181,100);\n"
"border-right-style: solid;\n"
"border-width: 5px\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
" font: 75 14pt \"Open Sans\" ;\n"
" color:#171725;\n"
" text-align:left;\n"
" height:52px;\n"
" width : 250px;\n"
" border :none;\n"
" padding-left:10px;\n"
"padding-right:10px;\n"
"border-left-color:#F7F8F9;\n"
"border-left-style: solid;\n"
"border-width: 3.2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"color:#103782;\n"
"background-color:#eaedf2;\n"
"border-left-color: rgb(16, 55, 130);\n"
"border-left-style: outset;\n"
"border-width: 3.2px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#ECF1F7;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 15, 9)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.navHome = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navHome.setFont(font)
        self.navHome.setStyleSheet("border-right-color:rgba(247, 248, 249,100);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Insight_Home3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Insight_Home1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navHome.setIcon(icon2)
        self.navHome.setIconSize(QtCore.QSize(25, 25))
        self.navHome.setCheckable(True)
        self.navHome.setAutoExclusive(True)
        self.navHome.setObjectName("navHome")
        self.verticalLayout.addWidget(self.navHome)
        self.navExport = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navExport.setFont(font)
        self.navExport.setStyleSheet("border-right-color:rgba(247, 248, 249,100);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Insight_Export3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Insight_Export1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navExport.setIcon(icon3)
        self.navExport.setIconSize(QtCore.QSize(25, 25))
        self.navExport.setCheckable(True)
        self.navExport.setAutoExclusive(True)
        self.navExport.setObjectName("navExport")
        self.verticalLayout.addWidget(self.navExport)
        self.navLog = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navLog.setFont(font)
        self.navLog.setStyleSheet("border-right-color:rgba(247, 248, 249,100);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Insight_Lopg3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Insight_Log1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navLog.setIcon(icon4)
        self.navLog.setIconSize(QtCore.QSize(25, 25))
        self.navLog.setCheckable(True)
        self.navLog.setAutoExclusive(True)
        self.navLog.setObjectName("navLog")
        self.verticalLayout.addWidget(self.navLog)
        self.navHelp = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navHelp.setFont(font)
        self.navHelp.setStyleSheet("border-right-color:rgba(247, 248, 249,100);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Insight_Help3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Insight_Help1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navHelp.setIcon(icon5)
        self.navHelp.setIconSize(QtCore.QSize(25, 25))
        self.navHelp.setCheckable(True)
        self.navHelp.setAutoExclusive(True)
        self.navHelp.setObjectName("navHelp")
        self.verticalLayout.addWidget(self.navHelp)
        self.navAbout = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navAbout.setFont(font)
        self.navAbout.setStyleSheet("border-right-color:rgba(247, 248, 249,100);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Insight_About3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Insight_About1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navAbout.setIcon(icon6)
        self.navAbout.setIconSize(QtCore.QSize(25, 25))
        self.navAbout.setCheckable(True)
        self.navAbout.setAutoExclusive(True)
        self.navAbout.setObjectName("navAbout")
        self.verticalLayout.addWidget(self.navAbout)
        self.navImp = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.navImp.setFont(font)
        self.navImp.setStyleSheet("\n"
"width : 250px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Insight_Settings3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Insight_Settings1_3.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navImp.setIcon(icon7)
        self.navImp.setIconSize(QtCore.QSize(25, 25))
        self.navImp.setCheckable(True)
        self.navImp.setAutoExclusive(True)
        self.navImp.setObjectName("navImp")
        self.verticalLayout.addWidget(self.navImp)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(270, 50, 1601, 961))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.widget_4 = QtWidgets.QWidget(self.homePage)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 1601, 961))
        self.widget_4.setStyleSheet("QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1100, 10, 451, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnDisconnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDisconnect.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnDisconnect.setCheckable(True)
        self.btnDisconnect.setAutoExclusive(True)
        self.btnDisconnect.setAutoDefault(False)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.gridLayout.addWidget(self.btnDisconnect, 0, 1, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnConnect.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnConnect.setCheckable(True)
        self.btnConnect.setAutoExclusive(True)
        self.btnConnect.setAutoDefault(False)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout.addWidget(self.btnConnect, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 90, 1451, 841))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_web = QtWidgets.QVBoxLayout()
        self.verticalLayout_web.setSpacing(0)
        self.verticalLayout_web.setObjectName("verticalLayout_web")
        self.widget_11 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_web.addWidget(self.widget_11)
        self.gridLayout_5.addLayout(self.verticalLayout_web, 0, 1, 1, 1)
        self.verticalLayout_bar = QtWidgets.QVBoxLayout()
        self.verticalLayout_bar.setSpacing(0)
        self.verticalLayout_bar.setObjectName("verticalLayout_bar")
        self.widget_10 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_bar.addWidget(self.widget_10)
        self.gridLayout_5.addLayout(self.verticalLayout_bar, 0, 0, 1, 1)
        self.textStatus = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textStatus.setStyleSheet("font: 10pt \"Open Sans\";\n"
"color:#171725;\n"
"background-color: rgb(247, 248, 249);\n"
"\n"
"")
        self.textStatus.setObjectName("textStatus")
        self.gridLayout_5.addWidget(self.textStatus, 1, 0, 1, 1)
        self.liveTableDataView = QtWidgets.QTableView(self.gridLayoutWidget_2)
        self.liveTableDataView.setStyleSheet("background-color: rgb(236, 241, 247);")
        self.liveTableDataView.setAlternatingRowColors(True)
        self.liveTableDataView.setIconSize(QtCore.QSize(0, 100))
        self.liveTableDataView.setShowGrid(False)
        self.liveTableDataView.setObjectName("liveTableDataView")
        self.gridLayout_5.addWidget(self.liveTableDataView, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.homePage)
        self.exportPage = QtWidgets.QWidget()
        self.exportPage.setObjectName("exportPage")
        self.table_view = QtWidgets.QTableView(self.exportPage)
        self.table_view.setGeometry(QtCore.QRect(80, 90, 1391, 781))
        self.table_view.setStyleSheet("background-color: rgb(236, 241, 247);")
        self.table_view.setAlternatingRowColors(True)
        self.table_view.setIconSize(QtCore.QSize(0, 100))
        self.table_view.setShowGrid(False)
        self.table_view.setObjectName("table_view")
        self.label_2 = QtWidgets.QLabel(self.exportPage)
        self.label_2.setGeometry(QtCore.QRect(186, 20, 60, 44))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#ECF1F7;")
        self.label_2.setObjectName("label_2")
        self.from_time = QtWidgets.QDateTimeEdit(self.exportPage)
        self.from_time.setGeometry(QtCore.QRect(248, 24, 252, 41))
        self.from_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.from_time.setDate(QtCore.QDate(2024, 1, 1))
        self.from_time.setTime(QtCore.QTime(0, 0, 0))
        self.from_time.setMinimumDate(QtCore.QDate(2024, 1, 1))
        self.from_time.setTimeSpec(QtCore.Qt.LocalTime)
        self.from_time.setObjectName("from_time")
        self.label_3 = QtWidgets.QLabel(self.exportPage)
        self.label_3.setGeometry(QtCore.QRect(508, 24, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:#ECF1F7;")
        self.label_3.setObjectName("label_3")
        self.to_time = QtWidgets.QDateTimeEdit(self.exportPage)
        self.to_time.setGeometry(QtCore.QRect(557, 21, 251, 41))
        self.to_time.setDate(QtCore.QDate(2024, 1, 1))
        self.to_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.to_time.setObjectName("to_time")
        self.widget_8 = QtWidgets.QWidget(self.exportPage)
        self.widget_8.setGeometry(QtCore.QRect(-10, 0, 1611, 960))
        self.widget_8.setStyleSheet("\n"
"QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.layoutWidget = QtWidgets.QWidget(self.widget_8)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 0, 651, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.show_data_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_data_btn.setFont(font)
        self.show_data_btn.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}\n"
"\n"
"\n"
"")
        self.show_data_btn.setCheckable(True)
        self.show_data_btn.setAutoExclusive(True)
        self.show_data_btn.setObjectName("show_data_btn")
        self.gridLayout_4.addWidget(self.show_data_btn, 0, 2, 1, 1)
        self.export_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.export_btn.setFont(font)
        self.export_btn.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.export_btn.setCheckable(True)
        self.export_btn.setAutoExclusive(True)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout_4.addWidget(self.export_btn, 0, 1, 1, 1)
        self.btnShowGraph = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnShowGraph.setFont(font)
        self.btnShowGraph.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnShowGraph.setCheckable(True)
        self.btnShowGraph.setAutoExclusive(True)
        self.btnShowGraph.setObjectName("btnShowGraph")
        self.gridLayout_4.addWidget(self.btnShowGraph, 0, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget_8)
        self.progressBar.setGeometry(QtCore.QRect(1290, 890, 191, 21))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.hrSelect = QtWidgets.QComboBox(self.widget_8)
        self.hrSelect.setGeometry(QtCore.QRect(90, 30, 101, 41))
        self.hrSelect.setStyleSheet("")
        self.hrSelect.setObjectName("hrSelect")
        self.hrSelect.addItem("")
        self.hrSelect.addItem("")
        self.hrSelect.addItem("")
        self.hrSelect.addItem("")
        self.hrSelect.addItem("")
        self.hrSelect.addItem("")
        self.widget_8.raise_()
        self.table_view.raise_()
        self.label_2.raise_()
        self.from_time.raise_()
        self.label_3.raise_()
        self.to_time.raise_()
        self.stackedWidget.addWidget(self.exportPage)
        self.logPage = QtWidgets.QWidget()
        self.logPage.setObjectName("logPage")
        self.widget_9 = QtWidgets.QWidget(self.logPage)
        self.widget_9.setGeometry(QtCore.QRect(0, 0, 1601, 951))
        self.widget_9.setStyleSheet("QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"\n"
"")
        self.widget_9.setObjectName("widget_9")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_9)
        self.layoutWidget1.setGeometry(QtCore.QRect(440, 10, 710, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(150, 10, 150, 10)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnClearLog = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnClearLog.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnClearLog.setCheckable(True)
        self.btnClearLog.setAutoExclusive(True)
        self.btnClearLog.setObjectName("btnClearLog")
        self.gridLayout_3.addWidget(self.btnClearLog, 0, 0, 1, 1)
        self.btnBackup = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnBackup.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnBackup.setCheckable(True)
        self.btnBackup.setAutoExclusive(True)
        self.btnBackup.setObjectName("btnBackup")
        self.gridLayout_3.addWidget(self.btnBackup, 0, 1, 1, 1)
        self.logField = QtWidgets.QTextBrowser(self.logPage)
        self.logField.setGeometry(QtCore.QRect(90, 90, 1401, 761))
        self.logField.setStyleSheet("font: 10pt  \"Open Sans\";\n"
"background-color: rgb(247, 248, 249);\n"
"color:#171725;\n"
"\n"
"")
        self.logField.setObjectName("logField")
        self.stackedWidget.addWidget(self.logPage)
        self.helpPage = QtWidgets.QWidget()
        self.helpPage.setObjectName("helpPage")
        self.widget_6 = QtWidgets.QWidget(self.helpPage)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 1601, 961))
        self.widget_6.setStyleSheet("QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.stackedWidget.addWidget(self.helpPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.widget_7 = QtWidgets.QWidget(self.aboutPage)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 1601, 951))
        self.widget_7.setStyleSheet("QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(1320, 813, 170, 51))
        self.label_7.setStyleSheet("font: 8pt \"Poppins\";")
        self.label_7.setObjectName("label_7")
        self.versionSet = QtWidgets.QLabel(self.widget_7)
        self.versionSet.setGeometry(QtCore.QRect(1400, 813, 171, 51))
        self.versionSet.setStyleSheet("font: 8pt \"Poppins\";")
        self.versionSet.setText("")
        self.versionSet.setObjectName("versionSet")
        self.activateLicense = QtWidgets.QPushButton(self.widget_7)
        self.activateLicense.setGeometry(QtCore.QRect(1134, 830, 81, 21))
        self.activateLicense.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.activateLicense.setObjectName("activateLicense")
        self.licenseEnter = QtWidgets.QLineEdit(self.widget_7)
        self.licenseEnter.setGeometry(QtCore.QRect(720, 832, 409, 20))
        self.licenseEnter.setStyleSheet("")
        self.licenseEnter.setObjectName("licenseEnter")
        self.licenseLabel = QtWidgets.QLabel(self.widget_7)
        self.licenseLabel.setGeometry(QtCore.QRect(720, 810, 181, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.licenseLabel.setFont(font)
        self.licenseLabel.setObjectName("licenseLabel")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_7)
        self.textBrowser.setGeometry(QtCore.QRect(90, 40, 1401, 711))
        self.textBrowser.setStyleSheet("font: 14pt \"Open Sans\";\n"
" color:#171725;\n"
"background-color: #F7F8F9;")
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.aboutPage)
        self.importPage = QtWidgets.QWidget()
        self.importPage.setObjectName("importPage")
        self.widget_5 = QtWidgets.QWidget(self.importPage)
        self.widget_5.setGeometry(QtCore.QRect(-140, 0, 1741, 781))
        self.widget_5.setStyleSheet("QWidget{\n"
"background-color: #ECF1F7;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(580, 330, 621, 261))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 2, 11, 2)
        self.gridLayout_2.setHorizontalSpacing(29)
        self.gridLayout_2.setVerticalSpacing(45)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnDownloadExcel = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnDownloadExcel.setFont(font)
        self.btnDownloadExcel.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnDownloadExcel.setCheckable(True)
        self.btnDownloadExcel.setAutoExclusive(True)
        self.btnDownloadExcel.setObjectName("btnDownloadExcel")
        self.gridLayout_2.addWidget(self.btnDownloadExcel, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.btnImpExcel = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnImpExcel.setFont(font)
        self.btnImpExcel.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnImpExcel.setCheckable(True)
        self.btnImpExcel.setAutoExclusive(True)
        self.btnImpExcel.setObjectName("btnImpExcel")
        self.gridLayout_2.addWidget(self.btnImpExcel, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.btnDownloadReport = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnDownloadReport.setFont(font)
        self.btnDownloadReport.setStyleSheet("QPushButton{\n"
"background-color:#103782;\n"
"border-radius: 5px;\n"
"border:2px solid #103782;\n"
"height:40px;\n"
"width:150px;\n"
"font: 12pt \"Open Sans\";\n"
"color:#FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#1F62E2;\n"
"border:2px solid#1F62E2;\n"
"}\n"
"QPushButton:checked{\n"
"border:2px solid #103782;\n"
"background-color:#103782;\n"
"}")
        self.btnDownloadReport.setCheckable(True)
        self.btnDownloadReport.setAutoExclusive(True)
        self.btnDownloadReport.setObjectName("btnDownloadReport")
        self.gridLayout_2.addWidget(self.btnDownloadReport, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(1250, 130, 161, 61))
        self.label_8.setObjectName("label_8")
        self.inpRackSlot = QtWidgets.QLineEdit(self.widget_5)
        self.inpRackSlot.setGeometry(QtCore.QRect(1442, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inpRackSlot.setFont(font)
        self.inpRackSlot.setStyleSheet("")
        self.inpRackSlot.setObjectName("inpRackSlot")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(1254, 60, 121, 41))
        self.label_6.setObjectName("label_6")
        self.inpIp = QtWidgets.QLineEdit(self.widget_5)
        self.inpIp.setGeometry(QtCore.QRect(1440, 60, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inpIp.setFont(font)
        self.inpIp.setStyleSheet("")
        self.inpIp.setObjectName("inpIp")
        self.logImp = QtWidgets.QTextBrowser(self.importPage)
        self.logImp.setGeometry(QtCore.QRect(0, 810, 1601, 141))
        self.logImp.setObjectName("logImp")
        self.stackedWidget.addWidget(self.importPage)
        self.widget_3.raise_()
        self.stackedWidget.raise_()
        self.widget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1925, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.navHome.setText(_translate("MainWindow", "  Home"))
        self.navExport.setText(_translate("MainWindow", "  Export"))
        self.navLog.setText(_translate("MainWindow", "  Log"))
        self.navHelp.setText(_translate("MainWindow", "  Help"))
        self.navAbout.setText(_translate("MainWindow", "  About"))
        self.navImp.setText(_translate("MainWindow", "  Upload"))
        self.btnDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "  From :"))
        self.label_3.setText(_translate("MainWindow", "  To :"))
        self.show_data_btn.setText(_translate("MainWindow", "Show Data"))
        self.export_btn.setText(_translate("MainWindow", "Export Excel"))
        self.btnShowGraph.setText(_translate("MainWindow", "Show Graph"))
        self.hrSelect.setItemText(0, _translate("MainWindow", "1 Hr"))
        self.hrSelect.setItemText(1, _translate("MainWindow", "4 Hr"))
        self.hrSelect.setItemText(2, _translate("MainWindow", "8 Hr"))
        self.hrSelect.setItemText(3, _translate("MainWindow", "12 Hr"))
        self.hrSelect.setItemText(4, _translate("MainWindow", "24 Hr"))
        self.hrSelect.setItemText(5, _translate("MainWindow", "Custom"))
        self.btnClearLog.setText(_translate("MainWindow", "Clear"))
        self.btnBackup.setText(_translate("MainWindow", "BackUP"))
        self.label_7.setText(_translate("MainWindow", "Software  Version   : "))
        self.activateLicense.setText(_translate("MainWindow", "Activate"))
        self.licenseLabel.setText(_translate("MainWindow", "Enter License Key:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:10pt; font-weight:600;\">InsightPro</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:10pt;\">                          Welcome to InsightPro, your ultimate solution for efficient data handling, analytics, visualization from Programmable Logic Controllers (PLCs).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:10pt; font-weight:600;\">Introduction:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">InsightPro is a cutting-edge software designed to streamline the process of fetching data from PLCs, empowering you to delve deep into your industrial operations. With its robust analytics engine, InsightPro provides unparalleled insights into your data, uncovering trends, anomalies, and correlations that drive informed decision-making.</li>\n"
"<li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Visualizing your data is made easy with InsightPro\'s intuitive interface, allowing you to explore your data in meaningful ways. Whether you\'re monitoring production metrics, analyzing equipment performance, or optimizing processes, our visualization tools help you grasp the full picture with clarity and precision.</li>\n"
"<li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Experience the next level of PLC data management with InsightPro. Revolutionize your operations, maximize efficiency, and unlock the full potential of your industrial processes.</li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:10pt; font-weight:600;\">Who Can Benefit?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Manufacturers</span>: Streamline production processes, minimize downtime, and optimize resource utilization with real-time insights into equipment performance and production metrics.</li>\n"
"<li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Automation Engineers</span>: Enhance system performance and reliability by monitoring PLC data in real time and proactively addressing issues before they escalate.</li>\n"
"<li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Plant Managers</span>: Gain visibility into plant operations, track key performance indicators, and make data-driven decisions to improve overall efficiency and productivity.</li>\n"
"<li style=\" font-family:\'Poppins\'; font-size:10pt;\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Maintenance Teams</span>: Predict equipment failures, schedule preventive maintenance tasks, and ensure optimal equipment performance to minimize costly downtime</li></ul>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Poppins\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:10pt; font-weight:600;\">Contact Us  :  </span><span style=\" font-family:\'Poppins\'; font-size:10pt;\">info@proliteautomation.com</span></p></body></html>"))
        self.btnDownloadExcel.setText(_translate("MainWindow", "Download reference file"))
        self.label.setText(_translate("MainWindow", "Upload the new PLC DB Configuration"))
        self.label_5.setText(_translate("MainWindow", "For Reference, Download the PLC DB Configurable file"))
        self.btnImpExcel.setText(_translate("MainWindow", "Upload"))
        self.label_9.setText(_translate("MainWindow", "To Download Report"))
        self.btnDownloadReport.setText(_translate("MainWindow", "Download Report"))
        self.label_8.setText(_translate("MainWindow", "Enter Rack and Slot :"))
        self.label_6.setText(_translate("MainWindow", "Enter PLC IP  :"))
import main_resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
